language: node_js
node_js:
  - "0.11"
  - "0.10"

before_script: npm run-script gen-parser
script: npm test

notifications:
  email:
    recipients:
      - me@jlach.com
    on_success: never
    on_failure: always