language: node_js
node_js:
  - "0.11"
  - "0.10"

sudo: false

before_script: npm run gen-parser
script: npm test
after_success: npm run coveralls

notifications:
  email:
    recipients:
      - me@jlach.com
    on_success: never
    on_failure: always